### ISSUE TITLE
Searching when using tag categories could be streamlined

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#944]
**Is your feature request related to a problem? Please describe.**
When tag categories are enabled, you can no longer search for "kono*" to find "kono_subarashii_sekai_ni_shukufuku_wo!", because technically the tag is now "series:kono_subarashii_sekai_ni_shukufuku_wo!", and you didn't think to include the "*" at the beginning to cover the "series:" portion.

**Describe the solution you'd like**
The user experience should work as it did prior to tag categories, so "kono*" still finds tags that are categorized, but start with "kono". Obviously this should apply to whatever arbitrary categories that have been defined.

**Describe alternatives you've considered**
No results. D'oh! Add the star in front. Every single time. Kind of like stubbing your toe on that one piece of furniture.

**Additional context**
Honestly, since the tag categories are baked right into the tag string, I can see this being rather difficult unless there was a second lookup table of tags-without-categories that could be searched against in this case, and point back to the full tag. Even that could run into trouble if someone actually put in "series:kono*" - but really, who does that?

I could have sworn I came across a similar feature request in another bug, but I'll be damned if I can find it now. Maybe Github's search is no better, or maybe I just suck at searching and need all the help I can get.

**Comment by shish** [comment]
This got fixed in #630 :3

**Comment by diamondsw** [comment]
Cool - I'll look forward to the next Docker image build (doesn't appear to be working in :latest right now, but that might have been built just before this landed). :)

**Comment by shish** [comment]
Weird, the build from 12 hours before your comment should have included that o.o

To make sure I'm understanding correctly, the change is what makes this happen:

![Screenshot 2024-01-06 at 11 22 19](https://github.com/shish/shimmie2/assets/40659/9f11ea20-06f3-49ce-9533-7c3654777791)

(If I've misunderstood and you were talking about something else please reopen ^^)

**Comment by diamondsw** [comment]
It appears your solution depends on the tag autocomplete extension, which I'm not running (it has significant layout/visual issues, at least in Safari/Danbooru theme - I should probably file another issue for this). For your solution, typing part of a categorized tag name drops down the menu, and then you can select it from that menu.

In my case (without the menu) the search still fails. For instance, my original example of "kono*" gives no results, but "series:kono*" works as expected. Without tag categories, "kono*" works.

**Comment by shish** [comment]
Aha, ok - I think I was thinking of a different issue when I was reading this one ^^ Now that I'm not mixing up issues, yeah I agree with this one, being able to search across categories is a huge usability issue

**Comment by shish** [comment]
(TIL that only repository collaborators are allowed to reopen issues - there isn't even a setting to allow issue reporters to manage their own open/closed statuses -_- https://github.com/isaacs/github/issues/583 - maybe there's a bot for that, though perhaps that is overkill...)
